---
Name: tauri-update-server
---

SilverStripe\Assets\File:
  allowed_extensions:
    - deb
    - rpm
    - appimage
    - exe
    - msi
    - dmg

SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    deb:
      - 'application/octet-stream'
      - 'application/x-debian-package'
      - 'application/vnd.debian.binary-package'
    rpm:
      - 'application/octet-stream'
      - 'application\/x-rpm'
    appimage:
      - 'application/octet-stream'
      - 'application/x-executable'
    exe:
      - 'application/octet-stream'
      - 'application/x-msdownload'
      - 'application/msword'
    msi:
      - 'application/octet-stream'
      - 'application/x-msdownload'
      - 'application/msword'
      - 'application/x-msi'
    dmg:
      - 'application/octet-stream'
      - 'application\/x-dmg'
      - 'application/x-apple-diskimage'
      - 'application/x-newton-compatible-pkg'
