---
Name: tauri-update-server-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'update/$Application/$Target/$CurrentVersion': "SixF\\TUS\\Controller\\TauriUpdateServer"
    'api/v1/release/$Action': "SixF\\TUS\\Controller\\TauriUpdateServerApi"
